### ISSUE TITLE
Update Config Schema

### ISSUE THREAD

**Issue by mkrueger12** [EinStack/glide#76]
The field under 'id' needs to be updated from 'openai' to 'provider'

```yaml
routers:
  language:
    - id: test-router
      models:
        - id: openai
          openai:
            api_key: "sk"
        - id: cohere
          openai:
            api_key: ""
```
