### ISSUE TITLE
Router Deployment Error

### ISSUE THREAD

**Issue by mkrueger12** [EinStack/glide#82]
Receiving following error when deploying the following config:

`panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x10509150c]`

```yaml
telemetry:
logging:
level: info
encoding: console # console, json
# other configs

api:
http:
listen_addr: 0.0.0.0:7685
max_body_size: "2Mi"
tls:
  ca_path:
  cert_path:
# other configs

routes:
language:
- id: openai-pool
  strategy: priority # round-robin, weighted-round-robin, priority, least-latency, priority, etc.
  models:
    - id: primary
      openai: # cohere, azureopenai, gemini, other providers we support
        model: gpt-3.5-turbo
        api_key: "sk-"
        default_params:
          temperature: 0.1

    - id: secondary
      cohere:
        model: command-light
        apiKey: ""
        default_params: # set the default request params
          temperature: 0.1

- id: latency-critical-pool
  strategy: least-latency
  models:
    - id: primary
      timeout_ms: 200
      openai:
        model: gpt-3.5-turbo
        api_key: "sk-"
     
    - id: secondary
      timeout_ms: 200
      cohere:
        api_key: ""

- id: cohere-openai-ab-test
  strategy: weighted-round-robin
  models:
    - id: openai
      weight: 30
      openai:
        api_key: "sk-"
    - id: cohere
      weight: 70
      cohere:
        api_key: ""
```

API keys redacted.

**Comment by mkrueger12** [comment]
Issue is with YAML formatting. Telemetry and API should be formatted like below:

```yaml
telemetry:
  logging:
    level: debug  # debug, info, warn, error, fatal
    encoding: console

api:
  http:
    listen_addr: 0.0.0.0:7685
    max_body_size: "2Mi"
    tls:
      ca_path:
      cert_path:
    # other configs
    ```
